/**
 * Embedded Weights Loader
 *
 * Loads MPNN weights from embedded binary data (compiled into executable).
 * No external file required!
 *
 * Usage:
 *   #include "pfalign/tools/weights/embedded_weights_loader.h"
 *
 *   auto [weights, config, sw_params] = load_embedded_mpnn_weights();
 *   // weights now loaded from compiled-in data (no file I/O!)
 *
 * Benefits:
 * - No file path dependencies
 * - Works anywhere (no weights file needed)
 * - Single binary distribution
 * - Faster startup (no file I/O)
 */

#pragma once

#include "pfalign/tools/weights/mpnn_weight_loader.h"
#include "pfalign/tools/weights/embedded_mpnn_weights.h"  // Generated by xxd
#include <vector>
#include <cstring>

namespace pfalign {
namespace weights {

/**
 * Load MPNN weights from embedded binary data.
 *
 * Loads weights from compiled-in data (no file access).
 *
 * @return Tuple of (MPNNWeights, MPNNConfig, SWParams)
 */
inline auto load_embedded_mpnn_weights() {
    // Create vector from embedded data
    std::vector<uint8_t> data(cpp_weights_data_v1_mpnn_weights_safetensors,
                              cpp_weights_data_v1_mpnn_weights_safetensors +
                                  cpp_weights_data_v1_mpnn_weights_safetensors_len);

    // Parse SafeTensors format from memory
    return MPNNWeightLoader::load_from_buffer(data);
}

/**
 * Get embedded weights as buffer.
 *
 * @return Pair of (data pointer, size)
 */
inline std::pair<const uint8_t*, size_t> get_embedded_weights_buffer() {
    return {cpp_weights_data_v1_mpnn_weights_safetensors,
            cpp_weights_data_v1_mpnn_weights_safetensors_len};
}

}  // namespace weights
}  // namespace pfalign
